// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.mlight.chat.protobuf;

public final class MessageProto {
	private MessageProto() {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface MessageOrBuilder extends
			// @@protoc_insertion_point(interface_extends:com.mlight.chat.protobuf.Message)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>required .com.mlight.chat.protobuf.Message.Type type = 1;</code>
		 */
		boolean hasType();

		/**
		 * <code>required .com.mlight.chat.protobuf.Message.Type type = 1;</code>
		 */
		com.mlight.chat.protobuf.MessageProto.Message.Type getType();

		/**
		 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
		 */
		java.util.List<Message.ParamFieldEntry> getParamFieldList();

		/**
		 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
		 */
		com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry getParamField(int index);

		/**
		 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
		 */
		int getParamFieldCount();

		/**
		 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
		 */
		java.util.List<? extends Message.ParamFieldEntryOrBuilder> getParamFieldOrBuilderList();

		/**
		 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
		 */
		com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntryOrBuilder getParamFieldOrBuilder(int index);

		/**
		 * <code>optional string body = 3;</code>
		 */
		boolean hasBody();

		/**
		 * <code>optional string body = 3;</code>
		 */
		String getBody();

		/**
		 * <code>optional string body = 3;</code>
		 */
		com.google.protobuf.ByteString getBodyBytes();
	}

	/**
	 * Protobuf type {@code com.mlight.chat.protobuf.Message}
	 */
	public static final class Message extends com.google.protobuf.GeneratedMessage implements
			// @@protoc_insertion_point(message_implements:com.mlight.chat.protobuf.Message)
			MessageOrBuilder {
		// Use Message.newBuilder() to construct.
		private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private Message(boolean noInit) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
		}

		private static final Message defaultInstance;

		public static Message getDefaultInstance() {
			return defaultInstance;
		}

		@Override
		public Message getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private Message(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 8: {
						int rawValue = input.readEnum();
						com.mlight.chat.protobuf.MessageProto.Message.Type value = com.mlight.chat.protobuf.MessageProto.Message.Type
								.valueOf(rawValue);
						if (value == null) {
							unknownFields.mergeVarintField(1, rawValue);
						} else {
							bitField0_ |= 0x00000001;
							type_ = value;
						}
						break;
					}
					case 18: {
						if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
							paramField_ = new java.util.ArrayList<ParamFieldEntry>();
							mutable_bitField0_ |= 0x00000002;
						}
						paramField_.add(
								input.readMessage(com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry.PARSER,
										extensionRegistry));
						break;
					}
					case 26: {
						com.google.protobuf.ByteString bs = input.readBytes();
						bitField0_ |= 0x00000002;
						body_ = bs;
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
			} finally {
				if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
					paramField_ = java.util.Collections.unmodifiableList(paramField_);
				}
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.mlight.chat.protobuf.MessageProto.internal_static_com_mlight_chat_protobuf_Message_descriptor;
		}

		@Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.mlight.chat.protobuf.MessageProto.internal_static_com_mlight_chat_protobuf_Message_fieldAccessorTable
					.ensureFieldAccessorsInitialized(com.mlight.chat.protobuf.MessageProto.Message.class,
							com.mlight.chat.protobuf.MessageProto.Message.Builder.class);
		}

		public static com.google.protobuf.Parser<Message> PARSER = new com.google.protobuf.AbstractParser<Message>() {
			@Override
			public Message parsePartialFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws com.google.protobuf.InvalidProtocolBufferException {
				return new Message(input, extensionRegistry);
			}
		};

		@Override
		public com.google.protobuf.Parser<Message> getParserForType() {
			return PARSER;
		}

		/**
		 * Protobuf enum {@code com.mlight.chat.protobuf.Message.Type}
		 */
		public enum Type implements com.google.protobuf.ProtocolMessageEnum {
			/**
			 * <code>MESSAGE = 0;</code>
			 */
			MESSAGE(0, 0),
			/**
			 * <code>REPLY = 1;</code>
			 */
			REPLY(1, 1),
			/**
			 * <code>REQUEST = 2;</code>
			 */
			REQUEST(2, 2),
			/**
			 * <code>RESPONSE = 3;</code>
			 */
			RESPONSE(3, 3),
			/**
			 * <code>PING = 4;</code>
			 */
			PING(4, 4),
			/**
			 * <code>PONG = 5;</code>
			 */
			PONG(5, 5),;

			/**
			 * <code>MESSAGE = 0;</code>
			 */
			public static final int MESSAGE_VALUE = 0;
			/**
			 * <code>REPLY = 1;</code>
			 */
			public static final int REPLY_VALUE = 1;
			/**
			 * <code>REQUEST = 2;</code>
			 */
			public static final int REQUEST_VALUE = 2;
			/**
			 * <code>RESPONSE = 3;</code>
			 */
			public static final int RESPONSE_VALUE = 3;
			/**
			 * <code>PING = 4;</code>
			 */
			public static final int PING_VALUE = 4;
			/**
			 * <code>PONG = 5;</code>
			 */
			public static final int PONG_VALUE = 5;

			@Override
			public final int getNumber() {
				return value;
			}

			public static Type valueOf(int value) {
				switch (value) {
				case 0:
					return MESSAGE;
				case 1:
					return REPLY;
				case 2:
					return REQUEST;
				case 3:
					return RESPONSE;
				case 4:
					return PING;
				case 5:
					return PONG;
				default:
					return null;
				}
			}

			public static com.google.protobuf.Internal.EnumLiteMap<Type> internalGetValueMap() {
				return internalValueMap;
			}

			private static com.google.protobuf.Internal.EnumLiteMap<Type> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<Type>() {
				@Override
				public Type findValueByNumber(int number) {
					return Type.valueOf(number);
				}
			};

			@Override
			public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
				return getDescriptor().getValues().get(index);
			}

			@Override
			public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
				return getDescriptor();
			}

			public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
				return com.mlight.chat.protobuf.MessageProto.Message.getDescriptor().getEnumTypes().get(0);
			}

			private static final Type[] VALUES = values();

			public static Type valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
				if (desc.getType() != getDescriptor()) {
					throw new IllegalArgumentException("EnumValueDescriptor is not for this type.");
				}
				return VALUES[desc.getIndex()];
			}

			private final int index;
			private final int value;

			private Type(int index, int value) {
				this.index = index;
				this.value = value;
			}

			// @@protoc_insertion_point(enum_scope:com.mlight.chat.protobuf.Message.Type)
		}

		public interface ParamFieldEntryOrBuilder extends
				// @@protoc_insertion_point(interface_extends:com.mlight.chat.protobuf.Message.ParamFieldEntry)
				com.google.protobuf.MessageOrBuilder {

			/**
			 * <code>required string name = 1;</code>
			 */
			boolean hasName();

			/**
			 * <code>required string name = 1;</code>
			 */
			String getName();

			/**
			 * <code>required string name = 1;</code>
			 */
			com.google.protobuf.ByteString getNameBytes();

			/**
			 * <code>required string value = 2;</code>
			 */
			boolean hasValue();

			/**
			 * <code>required string value = 2;</code>
			 */
			String getValue();

			/**
			 * <code>required string value = 2;</code>
			 */
			com.google.protobuf.ByteString getValueBytes();
		}

		/**
		 * Protobuf type
		 * {@code com.mlight.chat.protobuf.Message.ParamFieldEntry}
		 */
		public static final class ParamFieldEntry extends com.google.protobuf.GeneratedMessage implements
				// @@protoc_insertion_point(message_implements:com.mlight.chat.protobuf.Message.ParamFieldEntry)
				ParamFieldEntryOrBuilder {
			// Use ParamFieldEntry.newBuilder() to construct.
			private ParamFieldEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
				super(builder);
				this.unknownFields = builder.getUnknownFields();
			}

			private ParamFieldEntry(boolean noInit) {
				this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
			}

			private static final ParamFieldEntry defaultInstance;

			public static ParamFieldEntry getDefaultInstance() {
				return defaultInstance;
			}

			@Override
			public ParamFieldEntry getDefaultInstanceForType() {
				return defaultInstance;
			}

			private final com.google.protobuf.UnknownFieldSet unknownFields;

			@Override
			public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
				return this.unknownFields;
			}

			private ParamFieldEntry(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws com.google.protobuf.InvalidProtocolBufferException {
				initFields();
				int mutable_bitField0_ = 0;
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder();
				try {
					boolean done = false;
					while (!done) {
						int tag = input.readTag();
						switch (tag) {
						case 0:
							done = true;
							break;
						default: {
							if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
						case 10: {
							com.google.protobuf.ByteString bs = input.readBytes();
							bitField0_ |= 0x00000001;
							name_ = bs;
							break;
						}
						case 18: {
							com.google.protobuf.ByteString bs = input.readBytes();
							bitField0_ |= 0x00000002;
							value_ = bs;
							break;
						}
						}
					}
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.setUnfinishedMessage(this);
				} catch (java.io.IOException e) {
					throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage())
							.setUnfinishedMessage(this);
				} finally {
					this.unknownFields = unknownFields.build();
					makeExtensionsImmutable();
				}
			}

			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.mlight.chat.protobuf.MessageProto.internal_static_com_mlight_chat_protobuf_Message_ParamFieldEntry_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.mlight.chat.protobuf.MessageProto.internal_static_com_mlight_chat_protobuf_Message_ParamFieldEntry_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry.class,
								com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry.Builder.class);
			}

			public static com.google.protobuf.Parser<ParamFieldEntry> PARSER = new com.google.protobuf.AbstractParser<ParamFieldEntry>() {
				@Override
				public ParamFieldEntry parsePartialFrom(com.google.protobuf.CodedInputStream input,
						com.google.protobuf.ExtensionRegistryLite extensionRegistry)
								throws com.google.protobuf.InvalidProtocolBufferException {
					return new ParamFieldEntry(input, extensionRegistry);
				}
			};

			@Override
			public com.google.protobuf.Parser<ParamFieldEntry> getParserForType() {
				return PARSER;
			}

			private int bitField0_;
			public static final int NAME_FIELD_NUMBER = 1;
			private Object name_;

			/**
			 * <code>required string name = 1;</code>
			 */
			@Override
			public boolean hasName() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>required string name = 1;</code>
			 */
			@Override
			public String getName() {
				Object ref = name_;
				if (ref instanceof String) {
					return (String) ref;
				} else {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						name_ = s;
					}
					return s;
				}
			}

			/**
			 * <code>required string name = 1;</code>
			 */
			@Override
			public com.google.protobuf.ByteString getNameBytes() {
				Object ref = name_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
					name_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			public static final int VALUE_FIELD_NUMBER = 2;
			private Object value_;

			/**
			 * <code>required string value = 2;</code>
			 */
			@Override
			public boolean hasValue() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			/**
			 * <code>required string value = 2;</code>
			 */
			@Override
			public String getValue() {
				Object ref = value_;
				if (ref instanceof String) {
					return (String) ref;
				} else {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						value_ = s;
					}
					return s;
				}
			}

			/**
			 * <code>required string value = 2;</code>
			 */
			@Override
			public com.google.protobuf.ByteString getValueBytes() {
				Object ref = value_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
					value_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			private void initFields() {
				name_ = "";
				value_ = "";
			}

			private byte memoizedIsInitialized = -1;

			@Override
			public final boolean isInitialized() {
				byte isInitialized = memoizedIsInitialized;
				if (isInitialized == 1)
					return true;
				if (isInitialized == 0)
					return false;

				if (!hasName()) {
					memoizedIsInitialized = 0;
					return false;
				}
				if (!hasValue()) {
					memoizedIsInitialized = 0;
					return false;
				}
				memoizedIsInitialized = 1;
				return true;
			}

			@Override
			public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
				getSerializedSize();
				if (((bitField0_ & 0x00000001) == 0x00000001)) {
					output.writeBytes(1, getNameBytes());
				}
				if (((bitField0_ & 0x00000002) == 0x00000002)) {
					output.writeBytes(2, getValueBytes());
				}
				getUnknownFields().writeTo(output);
			}

			private int memoizedSerializedSize = -1;

			@Override
			public int getSerializedSize() {
				int size = memoizedSerializedSize;
				if (size != -1)
					return size;

				size = 0;
				if (((bitField0_ & 0x00000001) == 0x00000001)) {
					size += com.google.protobuf.CodedOutputStream.computeBytesSize(1, getNameBytes());
				}
				if (((bitField0_ & 0x00000002) == 0x00000002)) {
					size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, getValueBytes());
				}
				size += getUnknownFields().getSerializedSize();
				memoizedSerializedSize = size;
				return size;
			}

			private static final long serialVersionUID = 0L;

			@Override
			protected Object writeReplace() throws java.io.ObjectStreamException {
				return super.writeReplace();
			}

			public static com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry parseFrom(
					com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry parseFrom(
					com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry parseFrom(byte[] data)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry parseFrom(byte[] data,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry parseFrom(
					java.io.InputStream input) throws java.io.IOException {
				return PARSER.parseFrom(input);
			}

			public static com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry parseFrom(
					java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws java.io.IOException {
				return PARSER.parseFrom(input, extensionRegistry);
			}

			public static com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry parseDelimitedFrom(
					java.io.InputStream input) throws java.io.IOException {
				return PARSER.parseDelimitedFrom(input);
			}

			public static com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry parseDelimitedFrom(
					java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws java.io.IOException {
				return PARSER.parseDelimitedFrom(input, extensionRegistry);
			}

			public static com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry parseFrom(
					com.google.protobuf.CodedInputStream input) throws java.io.IOException {
				return PARSER.parseFrom(input);
			}

			public static com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry parseFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				return PARSER.parseFrom(input, extensionRegistry);
			}

			public static Builder newBuilder() {
				return Builder.create();
			}

			@Override
			public Builder newBuilderForType() {
				return newBuilder();
			}

			public static Builder newBuilder(com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry prototype) {
				return newBuilder().mergeFrom(prototype);
			}

			@Override
			public Builder toBuilder() {
				return newBuilder(this);
			}

			@Override
			protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				Builder builder = new Builder(parent);
				return builder;
			}

			/**
			 * Protobuf type
			 * {@code com.mlight.chat.protobuf.Message.ParamFieldEntry}
			 */
			public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
					// @@protoc_insertion_point(builder_implements:com.mlight.chat.protobuf.Message.ParamFieldEntry)
					com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntryOrBuilder {
				public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
					return com.mlight.chat.protobuf.MessageProto.internal_static_com_mlight_chat_protobuf_Message_ParamFieldEntry_descriptor;
				}

				@Override
				protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
					return com.mlight.chat.protobuf.MessageProto.internal_static_com_mlight_chat_protobuf_Message_ParamFieldEntry_fieldAccessorTable
							.ensureFieldAccessorsInitialized(
									com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry.class,
									com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry.Builder.class);
				}

				// Construct using
				// com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry.newBuilder()
				private Builder() {
					maybeForceBuilderInitialization();
				}

				private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
					super(parent);
					maybeForceBuilderInitialization();
				}

				private void maybeForceBuilderInitialization() {
					if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					}
				}

				private static Builder create() {
					return new Builder();
				}

				@Override
				public Builder clear() {
					super.clear();
					name_ = "";
					bitField0_ = (bitField0_ & ~0x00000001);
					value_ = "";
					bitField0_ = (bitField0_ & ~0x00000002);
					return this;
				}

				@Override
				public Builder clone() {
					return create().mergeFrom(buildPartial());
				}

				@Override
				public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
					return com.mlight.chat.protobuf.MessageProto.internal_static_com_mlight_chat_protobuf_Message_ParamFieldEntry_descriptor;
				}

				@Override
				public com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry getDefaultInstanceForType() {
					return com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry.getDefaultInstance();
				}

				@Override
				public com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry build() {
					com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry result = buildPartial();
					if (!result.isInitialized()) {
						throw newUninitializedMessageException(result);
					}
					return result;
				}

				@Override
				public com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry buildPartial() {
					com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry result = new com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry(
							this);
					int from_bitField0_ = bitField0_;
					int to_bitField0_ = 0;
					if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
						to_bitField0_ |= 0x00000001;
					}
					result.name_ = name_;
					if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
						to_bitField0_ |= 0x00000002;
					}
					result.value_ = value_;
					result.bitField0_ = to_bitField0_;
					onBuilt();
					return result;
				}

				@Override
				public Builder mergeFrom(com.google.protobuf.Message other) {
					if (other instanceof com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry) {
						return mergeFrom((com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry) other);
					} else {
						super.mergeFrom(other);
						return this;
					}
				}

				public Builder mergeFrom(com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry other) {
					if (other == com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry.getDefaultInstance())
						return this;
					if (other.hasName()) {
						bitField0_ |= 0x00000001;
						name_ = other.name_;
						onChanged();
					}
					if (other.hasValue()) {
						bitField0_ |= 0x00000002;
						value_ = other.value_;
						onChanged();
					}
					this.mergeUnknownFields(other.getUnknownFields());
					return this;
				}

				@Override
				public final boolean isInitialized() {
					if (!hasName()) {

						return false;
					}
					if (!hasValue()) {

						return false;
					}
					return true;
				}

				@Override
				public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
						com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
					com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry parsedMessage = null;
					try {
						parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
					} catch (com.google.protobuf.InvalidProtocolBufferException e) {
						parsedMessage = (com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry) e
								.getUnfinishedMessage();
						throw e;
					} finally {
						if (parsedMessage != null) {
							mergeFrom(parsedMessage);
						}
					}
					return this;
				}

				private int bitField0_;

				private Object name_ = "";

				/**
				 * <code>required string name = 1;</code>
				 */
				@Override
				public boolean hasName() {
					return ((bitField0_ & 0x00000001) == 0x00000001);
				}

				/**
				 * <code>required string name = 1;</code>
				 */
				@Override
				public String getName() {
					Object ref = name_;
					if (!(ref instanceof String)) {
						com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
						String s = bs.toStringUtf8();
						if (bs.isValidUtf8()) {
							name_ = s;
						}
						return s;
					} else {
						return (String) ref;
					}
				}

				/**
				 * <code>required string name = 1;</code>
				 */
				@Override
				public com.google.protobuf.ByteString getNameBytes() {
					Object ref = name_;
					if (ref instanceof String) {
						com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
						name_ = b;
						return b;
					} else {
						return (com.google.protobuf.ByteString) ref;
					}
				}

				/**
				 * <code>required string name = 1;</code>
				 */
				public Builder setName(String value) {
					if (value == null) {
						throw new NullPointerException();
					}
					bitField0_ |= 0x00000001;
					name_ = value;
					onChanged();
					return this;
				}

				/**
				 * <code>required string name = 1;</code>
				 */
				public Builder clearName() {
					bitField0_ = (bitField0_ & ~0x00000001);
					name_ = getDefaultInstance().getName();
					onChanged();
					return this;
				}

				/**
				 * <code>required string name = 1;</code>
				 */
				public Builder setNameBytes(com.google.protobuf.ByteString value) {
					if (value == null) {
						throw new NullPointerException();
					}
					bitField0_ |= 0x00000001;
					name_ = value;
					onChanged();
					return this;
				}

				private Object value_ = "";

				/**
				 * <code>required string value = 2;</code>
				 */
				@Override
				public boolean hasValue() {
					return ((bitField0_ & 0x00000002) == 0x00000002);
				}

				/**
				 * <code>required string value = 2;</code>
				 */
				@Override
				public String getValue() {
					Object ref = value_;
					if (!(ref instanceof String)) {
						com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
						String s = bs.toStringUtf8();
						if (bs.isValidUtf8()) {
							value_ = s;
						}
						return s;
					} else {
						return (String) ref;
					}
				}

				/**
				 * <code>required string value = 2;</code>
				 */
				@Override
				public com.google.protobuf.ByteString getValueBytes() {
					Object ref = value_;
					if (ref instanceof String) {
						com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
						value_ = b;
						return b;
					} else {
						return (com.google.protobuf.ByteString) ref;
					}
				}

				/**
				 * <code>required string value = 2;</code>
				 */
				public Builder setValue(String value) {
					if (value == null) {
						throw new NullPointerException();
					}
					bitField0_ |= 0x00000002;
					value_ = value;
					onChanged();
					return this;
				}

				/**
				 * <code>required string value = 2;</code>
				 */
				public Builder clearValue() {
					bitField0_ = (bitField0_ & ~0x00000002);
					value_ = getDefaultInstance().getValue();
					onChanged();
					return this;
				}

				/**
				 * <code>required string value = 2;</code>
				 */
				public Builder setValueBytes(com.google.protobuf.ByteString value) {
					if (value == null) {
						throw new NullPointerException();
					}
					bitField0_ |= 0x00000002;
					value_ = value;
					onChanged();
					return this;
				}

				// @@protoc_insertion_point(builder_scope:com.mlight.chat.protobuf.Message.ParamFieldEntry)
			}

			static {
				defaultInstance = new ParamFieldEntry(true);
				defaultInstance.initFields();
			}

			// @@protoc_insertion_point(class_scope:com.mlight.chat.protobuf.Message.ParamFieldEntry)
		}

		private int bitField0_;
		public static final int TYPE_FIELD_NUMBER = 1;
		private com.mlight.chat.protobuf.MessageProto.Message.Type type_;

		/**
		 * <code>required .com.mlight.chat.protobuf.Message.Type type = 1;</code>
		 */
		@Override
		public boolean hasType() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>required .com.mlight.chat.protobuf.Message.Type type = 1;</code>
		 */
		@Override
		public com.mlight.chat.protobuf.MessageProto.Message.Type getType() {
			return type_;
		}

		public static final int PARAM_FIELD_FIELD_NUMBER = 2;
		private java.util.List<ParamFieldEntry> paramField_;

		/**
		 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
		 */
		@Override
		public java.util.List<ParamFieldEntry> getParamFieldList() {
			return paramField_;
		}

		/**
		 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
		 */
		@Override
		public java.util.List<? extends ParamFieldEntryOrBuilder> getParamFieldOrBuilderList() {
			return paramField_;
		}

		/**
		 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
		 */
		@Override
		public int getParamFieldCount() {
			return paramField_.size();
		}

		/**
		 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
		 */
		@Override
		public com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry getParamField(int index) {
			return paramField_.get(index);
		}

		/**
		 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
		 */
		@Override
		public com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntryOrBuilder getParamFieldOrBuilder(
				int index) {
			return paramField_.get(index);
		}

		public static final int BODY_FIELD_NUMBER = 3;
		private Object body_;

		/**
		 * <code>optional string body = 3;</code>
		 */
		@Override
		public boolean hasBody() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		/**
		 * <code>optional string body = 3;</code>
		 */
		@Override
		public String getBody() {
			Object ref = body_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					body_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>optional string body = 3;</code>
		 */
		@Override
		public com.google.protobuf.ByteString getBodyBytes() {
			Object ref = body_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				body_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			type_ = com.mlight.chat.protobuf.MessageProto.Message.Type.MESSAGE;
			paramField_ = java.util.Collections.emptyList();
			body_ = "";
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			if (!hasType()) {
				memoizedIsInitialized = 0;
				return false;
			}
			for (int i = 0; i < getParamFieldCount(); i++) {
				if (!getParamField(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeEnum(1, type_.getNumber());
			}
			for (int i = 0; i < paramField_.size(); i++) {
				output.writeMessage(2, paramField_.get(i));
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(3, getBodyBytes());
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeEnumSize(1, type_.getNumber());
			}
			for (int i = 0; i < paramField_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(2, paramField_.get(i));
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(3, getBodyBytes());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@Override
		protected Object writeReplace() throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static com.mlight.chat.protobuf.MessageProto.Message parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.mlight.chat.protobuf.MessageProto.Message parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.mlight.chat.protobuf.MessageProto.Message parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.mlight.chat.protobuf.MessageProto.Message parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.mlight.chat.protobuf.MessageProto.Message parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static com.mlight.chat.protobuf.MessageProto.Message parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static com.mlight.chat.protobuf.MessageProto.Message parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static com.mlight.chat.protobuf.MessageProto.Message parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static com.mlight.chat.protobuf.MessageProto.Message parseFrom(
				com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static com.mlight.chat.protobuf.MessageProto.Message parseFrom(
				com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		@Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(com.mlight.chat.protobuf.MessageProto.Message prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		@Override
		public Builder toBuilder() {
			return newBuilder(this);
		}

		@Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code com.mlight.chat.protobuf.Message}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:com.mlight.chat.protobuf.Message)
				com.mlight.chat.protobuf.MessageProto.MessageOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.mlight.chat.protobuf.MessageProto.internal_static_com_mlight_chat_protobuf_Message_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.mlight.chat.protobuf.MessageProto.internal_static_com_mlight_chat_protobuf_Message_fieldAccessorTable
						.ensureFieldAccessorsInitialized(com.mlight.chat.protobuf.MessageProto.Message.class,
								com.mlight.chat.protobuf.MessageProto.Message.Builder.class);
			}

			// Construct using
			// com.mlight.chat.protobuf.MessageProto.Message.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getParamFieldFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			@Override
			public Builder clear() {
				super.clear();
				type_ = com.mlight.chat.protobuf.MessageProto.Message.Type.MESSAGE;
				bitField0_ = (bitField0_ & ~0x00000001);
				if (paramFieldBuilder_ == null) {
					paramField_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000002);
				} else {
					paramFieldBuilder_.clear();
				}
				body_ = "";
				bitField0_ = (bitField0_ & ~0x00000004);
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return com.mlight.chat.protobuf.MessageProto.internal_static_com_mlight_chat_protobuf_Message_descriptor;
			}

			@Override
			public com.mlight.chat.protobuf.MessageProto.Message getDefaultInstanceForType() {
				return com.mlight.chat.protobuf.MessageProto.Message.getDefaultInstance();
			}

			@Override
			public com.mlight.chat.protobuf.MessageProto.Message build() {
				com.mlight.chat.protobuf.MessageProto.Message result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@Override
			public com.mlight.chat.protobuf.MessageProto.Message buildPartial() {
				com.mlight.chat.protobuf.MessageProto.Message result = new com.mlight.chat.protobuf.MessageProto.Message(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.type_ = type_;
				if (paramFieldBuilder_ == null) {
					if (((bitField0_ & 0x00000002) == 0x00000002)) {
						paramField_ = java.util.Collections.unmodifiableList(paramField_);
						bitField0_ = (bitField0_ & ~0x00000002);
					}
					result.paramField_ = paramField_;
				} else {
					result.paramField_ = paramFieldBuilder_.build();
				}
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000002;
				}
				result.body_ = body_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.mlight.chat.protobuf.MessageProto.Message) {
					return mergeFrom((com.mlight.chat.protobuf.MessageProto.Message) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(com.mlight.chat.protobuf.MessageProto.Message other) {
				if (other == com.mlight.chat.protobuf.MessageProto.Message.getDefaultInstance())
					return this;
				if (other.hasType()) {
					setType(other.getType());
				}
				if (paramFieldBuilder_ == null) {
					if (!other.paramField_.isEmpty()) {
						if (paramField_.isEmpty()) {
							paramField_ = other.paramField_;
							bitField0_ = (bitField0_ & ~0x00000002);
						} else {
							ensureParamFieldIsMutable();
							paramField_.addAll(other.paramField_);
						}
						onChanged();
					}
				} else {
					if (!other.paramField_.isEmpty()) {
						if (paramFieldBuilder_.isEmpty()) {
							paramFieldBuilder_.dispose();
							paramFieldBuilder_ = null;
							paramField_ = other.paramField_;
							bitField0_ = (bitField0_ & ~0x00000002);
							paramFieldBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders
									? getParamFieldFieldBuilder() : null;
						} else {
							paramFieldBuilder_.addAllMessages(other.paramField_);
						}
					}
				}
				if (other.hasBody()) {
					bitField0_ |= 0x00000004;
					body_ = other.body_;
					onChanged();
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			@Override
			public final boolean isInitialized() {
				if (!hasType()) {

					return false;
				}
				for (int i = 0; i < getParamFieldCount(); i++) {
					if (!getParamField(i).isInitialized()) {

						return false;
					}
				}
				return true;
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				com.mlight.chat.protobuf.MessageProto.Message parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (com.mlight.chat.protobuf.MessageProto.Message) e.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			private com.mlight.chat.protobuf.MessageProto.Message.Type type_ = com.mlight.chat.protobuf.MessageProto.Message.Type.MESSAGE;

			/**
			 * <code>required .com.mlight.chat.protobuf.Message.Type type = 1;</code>
			 */
			@Override
			public boolean hasType() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>required .com.mlight.chat.protobuf.Message.Type type = 1;</code>
			 */
			@Override
			public com.mlight.chat.protobuf.MessageProto.Message.Type getType() {
				return type_;
			}

			/**
			 * <code>required .com.mlight.chat.protobuf.Message.Type type = 1;</code>
			 */
			public Builder setType(com.mlight.chat.protobuf.MessageProto.Message.Type value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				type_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required .com.mlight.chat.protobuf.Message.Type type = 1;</code>
			 */
			public Builder clearType() {
				bitField0_ = (bitField0_ & ~0x00000001);
				type_ = com.mlight.chat.protobuf.MessageProto.Message.Type.MESSAGE;
				onChanged();
				return this;
			}

			private java.util.List<ParamFieldEntry> paramField_ = java.util.Collections.emptyList();

			private void ensureParamFieldIsMutable() {
				if (!((bitField0_ & 0x00000002) == 0x00000002)) {
					paramField_ = new java.util.ArrayList<ParamFieldEntry>(paramField_);
					bitField0_ |= 0x00000002;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilder<com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry, com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry.Builder, com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntryOrBuilder> paramFieldBuilder_;

			/**
			 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
			 */
			@Override
			public java.util.List<ParamFieldEntry> getParamFieldList() {
				if (paramFieldBuilder_ == null) {
					return java.util.Collections.unmodifiableList(paramField_);
				} else {
					return paramFieldBuilder_.getMessageList();
				}
			}

			/**
			 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
			 */
			@Override
			public int getParamFieldCount() {
				if (paramFieldBuilder_ == null) {
					return paramField_.size();
				} else {
					return paramFieldBuilder_.getCount();
				}
			}

			/**
			 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
			 */
			@Override
			public com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry getParamField(int index) {
				if (paramFieldBuilder_ == null) {
					return paramField_.get(index);
				} else {
					return paramFieldBuilder_.getMessage(index);
				}
			}

			/**
			 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
			 */
			public Builder setParamField(int index,
					com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry value) {
				if (paramFieldBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureParamFieldIsMutable();
					paramField_.set(index, value);
					onChanged();
				} else {
					paramFieldBuilder_.setMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
			 */
			public Builder setParamField(int index,
					com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry.Builder builderForValue) {
				if (paramFieldBuilder_ == null) {
					ensureParamFieldIsMutable();
					paramField_.set(index, builderForValue.build());
					onChanged();
				} else {
					paramFieldBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
			 */
			public Builder addParamField(com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry value) {
				if (paramFieldBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureParamFieldIsMutable();
					paramField_.add(value);
					onChanged();
				} else {
					paramFieldBuilder_.addMessage(value);
				}
				return this;
			}

			/**
			 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
			 */
			public Builder addParamField(int index,
					com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry value) {
				if (paramFieldBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureParamFieldIsMutable();
					paramField_.add(index, value);
					onChanged();
				} else {
					paramFieldBuilder_.addMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
			 */
			public Builder addParamField(
					com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry.Builder builderForValue) {
				if (paramFieldBuilder_ == null) {
					ensureParamFieldIsMutable();
					paramField_.add(builderForValue.build());
					onChanged();
				} else {
					paramFieldBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
			 */
			public Builder addParamField(int index,
					com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry.Builder builderForValue) {
				if (paramFieldBuilder_ == null) {
					ensureParamFieldIsMutable();
					paramField_.add(index, builderForValue.build());
					onChanged();
				} else {
					paramFieldBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
			 */
			public Builder addAllParamField(Iterable<? extends ParamFieldEntry> values) {
				if (paramFieldBuilder_ == null) {
					ensureParamFieldIsMutable();
					com.google.protobuf.AbstractMessageLite.Builder.addAll(values, paramField_);
					onChanged();
				} else {
					paramFieldBuilder_.addAllMessages(values);
				}
				return this;
			}

			/**
			 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
			 */
			public Builder clearParamField() {
				if (paramFieldBuilder_ == null) {
					paramField_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000002);
					onChanged();
				} else {
					paramFieldBuilder_.clear();
				}
				return this;
			}

			/**
			 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
			 */
			public Builder removeParamField(int index) {
				if (paramFieldBuilder_ == null) {
					ensureParamFieldIsMutable();
					paramField_.remove(index);
					onChanged();
				} else {
					paramFieldBuilder_.remove(index);
				}
				return this;
			}

			/**
			 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
			 */
			public com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry.Builder getParamFieldBuilder(
					int index) {
				return getParamFieldFieldBuilder().getBuilder(index);
			}

			/**
			 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
			 */
			@Override
			public com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntryOrBuilder getParamFieldOrBuilder(
					int index) {
				if (paramFieldBuilder_ == null) {
					return paramField_.get(index);
				} else {
					return paramFieldBuilder_.getMessageOrBuilder(index);
				}
			}

			/**
			 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
			 */
			@Override
			public java.util.List<? extends ParamFieldEntryOrBuilder> getParamFieldOrBuilderList() {
				if (paramFieldBuilder_ != null) {
					return paramFieldBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(paramField_);
				}
			}

			/**
			 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
			 */
			public com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry.Builder addParamFieldBuilder() {
				return getParamFieldFieldBuilder()
						.addBuilder(com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry.getDefaultInstance());
			}

			/**
			 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
			 */
			public com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry.Builder addParamFieldBuilder(
					int index) {
				return getParamFieldFieldBuilder().addBuilder(index,
						com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry.getDefaultInstance());
			}

			/**
			 * <code>repeated .com.mlight.chat.protobuf.Message.ParamFieldEntry param_field = 2;</code>
			 */
			public java.util.List<ParamFieldEntry.Builder> getParamFieldBuilderList() {
				return getParamFieldFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilder<com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry, com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry.Builder, com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntryOrBuilder> getParamFieldFieldBuilder() {
				if (paramFieldBuilder_ == null) {
					paramFieldBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry, com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntry.Builder, com.mlight.chat.protobuf.MessageProto.Message.ParamFieldEntryOrBuilder>(
							paramField_, ((bitField0_ & 0x00000002) == 0x00000002), getParentForChildren(), isClean());
					paramField_ = null;
				}
				return paramFieldBuilder_;
			}

			private Object body_ = "";

			/**
			 * <code>optional string body = 3;</code>
			 */
			@Override
			public boolean hasBody() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			/**
			 * <code>optional string body = 3;</code>
			 */
			@Override
			public String getBody() {
				Object ref = body_;
				if (!(ref instanceof String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						body_ = s;
					}
					return s;
				} else {
					return (String) ref;
				}
			}

			/**
			 * <code>optional string body = 3;</code>
			 */
			@Override
			public com.google.protobuf.ByteString getBodyBytes() {
				Object ref = body_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
					body_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>optional string body = 3;</code>
			 */
			public Builder setBody(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000004;
				body_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional string body = 3;</code>
			 */
			public Builder clearBody() {
				bitField0_ = (bitField0_ & ~0x00000004);
				body_ = getDefaultInstance().getBody();
				onChanged();
				return this;
			}

			/**
			 * <code>optional string body = 3;</code>
			 */
			public Builder setBodyBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000004;
				body_ = value;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:com.mlight.chat.protobuf.Message)
		}

		static {
			defaultInstance = new Message(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:com.mlight.chat.protobuf.Message)
	}

	private static final com.google.protobuf.Descriptors.Descriptor internal_static_com_mlight_chat_protobuf_Message_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_com_mlight_chat_protobuf_Message_fieldAccessorTable;
	private static final com.google.protobuf.Descriptors.Descriptor internal_static_com_mlight_chat_protobuf_Message_ParamFieldEntry_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_com_mlight_chat_protobuf_Message_ParamFieldEntry_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

	static {
		String[] descriptorData = { "\n\rMessage.proto\022\030com.mlight.chat.protobu"
				+ "f\"\224\002\n\007Message\0224\n\004type\030\001 \002(\0162&.com.mlight"
				+ ".chat.protobuf.Message.Type\022F\n\013param_fie"
				+ "ld\030\002 \003(\01321.com.mlight.chat.protobuf.Mess"
				+ "age.ParamFieldEntry\022\014\n\004body\030\003 \001(\t\032.\n\017Par"
				+ "amFieldEntry\022\014\n\004name\030\001 \002(\t\022\r\n\005value\030\002 \002("
				+ "\t\"M\n\004Type\022\013\n\007MESSAGE\020\000\022\t\n\005REPLY\020\001\022\013\n\007REQ"
				+ "UEST\020\002\022\014\n\010RESPONSE\020\003\022\010\n\004PING\020\004\022\010\n\004PONG\020\005"
				+ "B-\n\030com.mlight.chat.protobufB\014MessagePro" + "toH\001\210\001\000" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			@Override
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
		internal_static_com_mlight_chat_protobuf_Message_descriptor = getDescriptor().getMessageTypes().get(0);
		internal_static_com_mlight_chat_protobuf_Message_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
				internal_static_com_mlight_chat_protobuf_Message_descriptor,
				new String[] { "Type", "ParamField", "Body", });
		internal_static_com_mlight_chat_protobuf_Message_ParamFieldEntry_descriptor = internal_static_com_mlight_chat_protobuf_Message_descriptor
				.getNestedTypes().get(0);
		internal_static_com_mlight_chat_protobuf_Message_ParamFieldEntry_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
				internal_static_com_mlight_chat_protobuf_Message_ParamFieldEntry_descriptor,
				new String[] { "Name", "Value", });
	}

	// @@protoc_insertion_point(outer_class_scope)
}
